name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stop default MySQL server
      run: sudo service mysql stop
    - name: Setup MariaDB
      run: |
        docker run \
        -e MYSQL_ROOT_PASSWORD=password \
        -e MYSQL_USER=moto-bot -e MYSQL_PASSWORD=password \
        -e MYSQL_DATABASE=moto-bot_test \
        -v ${GITHUB_WORKSPACE}/mysql/init:/docker-entrypoint-initdb.d \
        -d -p "3306:3306" mariadb:10.4.10
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Makes sure the source compiles
      run: mvn -B package --file pom.xml -D skipTests
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - name: Run tests
      run: mvn -B test --file pom.xml
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_DATABASE: moto-bot_test
        MYSQL_USER: moto-bot
        MYSQL_PASSWORD: password
        LOGBACK_TIMEZONE: Asia/Tokyo
